version: '3'
services:
  savedmodels:
    build:
      context: ./savedmodels
      dockerfile: Dockerfile

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - savedmodels
      